// Replaces Contentlayer (its CLI is broken on modern Node).
// Parses posts/*.md frontmatter + markdown body -> HTML,
// writes utils/generated-posts.js exporting `allPosts` with the
// same shape the old `contentlayer/generated` module provided.
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { remark } from "remark";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
  const postsDir = path.join(__dirname, "..", "posts");
  const files = fs
    .readdirSync(postsDir)
    .filter((f) => f.endsWith(".md"));

  const allPosts = [];
  for (const file of files) {
    const raw = fs.readFileSync(path.join(postsDir, file), "utf8");
    const { data, content } = matter(raw);
    const processed = await remark()
      .use(remarkRehype, { allowDangerousHtml: true })
      .use(rehypeStringify, { allowDangerousHtml: true })
      .process(content);
    const html = processed.toString();
    const slug = data.slug || file.replace(/\.md$/, "");

    allPosts.push({
      title: data.title || "",
      date: data.date ? new Date(data.date).toISOString() : "",
      author: data.author || "",
      description: data.description || "",
      slug,
      id: data.id ?? null,
      image: data.image || "",
      draft: data.draft ?? false,
      tags: data.tags || [],
      categories: data.categories || [],
      body: { html },
    });
  }

  const out = `// Auto-generated by scripts/build-content.mjs — do not edit.
export const allPosts = ${JSON.stringify(allPosts, null, 2)};
`;
  const outPath = path.join(__dirname, "..", "utils", "generated-posts.js");
  fs.writeFileSync(outPath, out);
  console.log(`generated-posts.js: ${allPosts.length} posts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
